version: "2.4"

services:
  alfresco:
    build: ./image
    mem_limit: 2g
    environment:
      - "JAVA_OPTS=-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
    ports:
      - 8082:8080
    volumes:
      - alfresco:/usr/local/tomcat/alf_data
      - ./data/alfresco-global.properties:/usr/local/tomcat/shared/classes/alfresco-global.properties
    depends_on:
      - postgres
      - activemq

  share:
    image: alfresco/alfresco-share:6.1.0-RC3
    mem_limit: 500m
    environment:
      - "JAVA_OPTS=-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      - REPO_HOST=alfresco
      - REPO_PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - alfresco

  postgres:
    image: postgres:11.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - postgres:/var/lib/postgresql/data

  solr6:
    image: alfresco/alfresco-search-services:1.4.0
    mem_limit: 1g
    environment:
      - "SOLR_JAVA_MEM=-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      - SOLR_ALFRESCO_SECURECOMMS=none
      - SOLR_SOLR_HOST=solr6
      - SOLR_SOLR_PORT=8983
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
    ports:
      - 8083:8983
    volumes:
      - solr6-data:/opt/alfresco-search-services/data
      - solr6-data:/opt/alfresco-search-services/contentstore
      - solr6-conf:/opt/alfresco-search-services/solrhome
      - solr6-conf:/opt/alfresco-search-services/keystores
    depends_on:
      - alfresco

  activemq:
    image: alfresco/alfresco-activemq:5.15.6
    ports:
      - 8161:8161
    volumes:
      - activemq-conf:/opt/activemq/conf
      - activemq-log:/var/log/activemq
      - activemq-data:/opt/activemq/data

  promena:
    image: promena-memory-http-activemq-executable:1.0.0
    mem_limit: 2g
    environment:
      - spring.activemq.broker-url=failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true
    ports:
      - 8090:8080

volumes:
  postgres:
  alfresco:
  solr6-data:
  solr6-conf:
  activemq-conf:
  activemq-log:
  activemq-data: