apiVersion: v1
kind: PersistentVolume
metadata:
  name: promena-communication
  namespace: promena
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/promena