apiVersion: v1
kind: Service
metadata:
  labels:
    app: promena
  name: promena
  namespace: promena
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: promena
  sessionAffinity: None
  type: LoadBalancer
